msg "Hey, buddy. This street is my turf." *line "I'd turn around if I were you." *wait
if ${global.hoodlum_jeff_talk_count} = 1
msg "(Wasn't this guy just across the street" *line "only a moment ago?)" *wait
if ${global.hoodlum_jeff_talk_count} = 2
msg "(How did he get across the street so fast...?!)" *wait
if ${global.hoodlum_jeff_talk_count} = 3
msg "(What is this sorcery?!)" *wait
if ${global.hoodlum_jeff_talk_count} > 3
msg "(....How?!?)" *wait
set global.hoodlum_jeff_talk_count ${global.hoodlum_jeff_talk_count} + 1 